### ISSUE TITLE
Output volumes have no effect on discrete outputs

### ISSUE THREAD

**Issue by amiguet** [essej/sooperlooper#46]
I have a session with 2 loops with discrete_io="yes".

The main outs follow the out volumes (both of individual loops and of main out), but if I connect a client directly to the discrete output of one of the loops, volume is always at max even if I modify the volume slider in the GUI.

I'm using a build from the latest sources on master on a Manjaro box with jack2.

Looks very much like a bug to me, but I might be missing something...

**Comment by essej** [comment]
There was a new feature added, "prefader" which when enabled (which it is now by default) means the discrete outputs are *not* affected by the output volumes (so you could mix them downstream instead). Just toggle the prefader option off on the loop to get the volume controls to affect it.

**Comment by amiguet** [comment]
Wow thanks for the very quick answer!

That was it, I hadn't seen the option. Sorry for the noise and thank you for your help!

**Comment by amiguet** [comment]
... And many thanks for your software! I've been using it on stage for more than 10 years :-D
